@startuml
title Diagramme de Séquence - Création d'Incident Asynchrone
skinparam sequence {
  LifeLineBorderColor #2E7D32
  ParticipantBorderColor #C62828
  ParticipantBackgroundColor White
}

actor Citoyen
participant "Frontend (Next.js)" as Front
participant "API Gateway (REST)" as API
participant "Service RMI (IA)" as IA
participant "MessageBroker (JMS)" as JMS

Citoyen -> Front : Soumet le formulaire d'incident
Front -> API : POST /api/v1/incidents (Token JWT)
activate API

API -> API : Vérification Sécurité (JWT Filter)

API -> IA : classifyIncident(text) [Appel Distant RMI]
activate IA
IA --> API : Retour JSON (Sévérité, Autorité)
deactivate IA

API -> API : Sauvegarde en Base (PostgreSQL)

API -> JMS : publish("urbanops.alert", Message) (Asynchrone)
activate JMS
API --> Front : 201 Created (Incident enregistré)
deactivate API
Front --> Citoyen : Affiche un succès

JMS --> JMS : Consommation asynchrone (Envoi Mail...)
deactivate JMS
@enduml
